name: Rearc Data Quest CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - sean/rearc-infra
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  build_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Test CDK
        run: |
          pip install -r infra/requirements-dev.txt
          pytest infra/tests/unit/test_rearc_quest_stack.py
      - name: CDK Synth
        if: github.event_name == 'push' && github.event.pull_request.merged == false
        run: cd infra && cdk synth RearcQuestStack
      - name: CDK Diff
        id: cdk_output
        if: github.event_name == 'push' && github.event.pull_request.merged == false
        run: cd infra && cdk diff RearcQuestStack
      - name: CDK Deploy
        if: github.event.pull_request.merged == true
        run: cd infra && cdk deploy RearcQuestStack
