name: Rearc Data Quest CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - sean/rearc-infra
  pull_request:
    branches: [main]
    types: [closed]


jobs:
  build_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: CDK Synth
        if: github.event_name == 'push' && github.event.pull_request.merged == false
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "synth"
          cdk_version: "1.16.2"
          working_dir: "infra"
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: CDK Diff
        if: github.event_name == 'push' && github.event.pull_request.merged == false
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          actions_comment: true
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      # - name: CDK Deploy
      #   if: github.event.pull_request.merged == true
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: "deploy"
      #     cdk_stack: "RearcQuestStack"
      #     cdk_args: "--require-approval never"
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: "us-east-1"
